# Chart.yaml
apiVersion: v2
name: nodejs-devops-app
description: A Helm chart for Node.js DevOps Application
type: application
version: 0.1.0
appVersion: "1.0.0"

# Métadonnées additionnelles
keywords:
  - nodejs
  - devops
  - microservice
home: https://github.com/MouradOuammou/nodejs-devops-app
sources:
  - https://github.com/MouradOuammou/nodejs-devops-app
maintainers:
  - name: Mourad Ouammou
    email: mourad.ouammou@example.com

# Version minimale de Kubernetes supportée
kubeVersion: ">=1.20.0"

# Dépendances (si nécessaire)
# dependencies:
#   - name: redis
#     version: "17.3.7"
#     repository: "https://charts.bitnami.com/bitnami"
#     condition: redis.enabled